"""PageIndex tree parsing, navigation, and text extraction.

This module provides the core interface to PageIndex JSON tree structures
generated by VectifyAI/PageIndex. It enables:
- Loading and validating tree JSON files
- Searching trees by title keywords, page ranges, and node IDs
- Extracting text content for specific tree nodes
"""

from finsight_core.pageindex.navigator import TreeNavigator
from finsight_core.pageindex.parser import load_tree, load_tree_from_dict
from finsight_core.pageindex.text_extractor import extract_node_text

__all__ = [
    "load_tree",
    "load_tree_from_dict",
    "TreeNavigator",
    "extract_node_text",
]
